version: "3"

services:
  ########################################
  # Elasticsearch: The log database
  ########################################
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.2"
    restart: always
    env_file: config/elasticsearch.env
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  ########################################
  # Logstash: The log ETL
  ########################################
  logstash:
    build: ./dockerfiles/logstash
    image: "ncarlier/logstash-elk:latest"
    restart: always
    env_file: config/logstash.env
    ports:
      - "${RSYSLOG_PORT:-5514}:5514"
      - "${SENDLOG_PORT:-9000}:9000"
    depends_on:
      - elasticsearch

  ########################################
  # Kibana: The log dashboard
  ########################################
  kibana:
    build: ./dockerfiles/kibana
    image: "ncarlier/kibana-elk:latest"
    restart: always
    env_file: config/kibana.env
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    depends_on:
      - elasticsearch

volumes:
  elastic-data:
